baseURL: "https://jinjinyan-oo/jinjinyan-oo.github.io/" 
title: Jinjin Yan
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        - name: Resume
          url: CV/
          weight: 1
        - name: Publications
          url: papers/
          weight: 2
      #  - name: Musicals
        #  url: courses/
        #  weight: 3
      #  - name: Photography
        #  url: design/
        #  weight: 4        

params:
    description: "This website hosts Pascal Michaillat's research papers, course materials, design templates, curriculum vitae, and a real-time business cycle dashboard."
    author: Jinjin Yan
    googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jinjin Yan
          subtitle: "Hello! I am a postdoctoral fellow in Developmental Psychology at Fordham University. I got my Ph.D. in Human Development and Family Sciences 
                     from University of Texas at Austin.
                    
                     <br><br>
                     In 2025/2026, I am on the academic job market!

                     <br><br>
                     My research focuses on understanding the health and well-being of ethnically-racially diverse adolescents and their parents within intersecting 
                     cultural, family, and neighborhood contexts. I have expertise in daily-level and longitudinal analyses, applying advanced statistical methods to
                     address questions in developmental and health sciences.

                     <br><br>
                     I grew up in Xi’an, one of the oldest cities in China with a history of over 3,000 years and the capital of thirteen ancient dynasties. 
                     Known as the starting point of the ancient Silk Road, Xi’an is home to iconic landmarks such as the Terracotta Army and its well-preserved city walls.

                     <br><br>
                     I’m passionate about Broadway and West End musicals 🎭, exploring the world 🌍, capturing moments through photography 📸, and caring 
                     for my plants 🌱.

                     <br> <br>

                    "
                     
          imageUrl: "/picture.jpeg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Resume
              url: CV/ 
            - name: Publications
              url: papers/
            #- name: Musicals
             # url: courses/
            #- name: Photography
             # url: design/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jinjinyan.67@gmail.com
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=HitQqrgAAAAJ
        - name: LinkedIn
          url: jinjin-yan-936300205
        - name: ORCID
          url: https://orcid.org/0000-0002-9278-3115

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Jinjin Yan"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true
