baseURL: "https://jinjinyan-oo/jinjinyan-oo.github.io/" 
title: Jinjin Yan
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        - name: Dashboard
          url: dashboard/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Design
          url: design/
          weight: 4        

params:
    description: "This website hosts Pascal Michaillat's research papers, course materials, design templates, curriculum vitae, and a real-time business cycle dashboard."
    author: Jinjin Yan
    googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jinjin Yan
          subtitle: "I am a postdoctoral fellow at Fordham University. I got my Ph.D. from University of Texas at Austin."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Dashboard
              url: dashboard/  
            - name: Publications
              url: papers/
            - name: Courses
              url: courses/
            - name: Design
              url: design/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: jinjinyan.67@gmail.com
        - name: Location
          url: location/
        - name: Office Hours 
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=HitQqrgAAAAJ
   

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Jinjin Yan"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true
