baseURL: "https://jinjinyan-oo/jinjinyan-oo.github.io/" 
title: Jinjin Yan
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        - name: Resume
          url: CV/
          weight: 1
        - name: Publications
          url: papers/
          weight: 2
        - name: Musicals
          url: courses/
          weight: 3
        - name: Photography
          url: design/
          weight: 4        

params:
    description: "This website hosts Pascal Michaillat's research papers, course materials, design templates, curriculum vitae, and a real-time business cycle dashboard."
    author: Jinjin Yan
    googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jinjin Yan
          subtitle: "Hello!I am a postdoctoral fellow in Developmental Psychology at Fordham University. I got my Ph.D. from University of Texas at Austin.
                     In 2025/2026, I will be on the academic job market."

            <br><br>
            My research projects at Purdue tackles the socio-technical aspects of Large Language Models (LLM). I  empirically
            study the correctness and quality issues of LLMs, and build interactive tools that can aid end-users in analyzing and understanding
            issues such as misinformation or stereotypes hidden in LLMs.

            <br><br>
            Before coming to Purdue, I received my M.Sc. in Computer Science and Engineering from Texas A&M University in May 2020.
            I completed my Bachelor's degree from Bangladesh University of Engineering and Technology (BUET). I grew up in the magical Dhaka city of Bangladesh.
            I love reading fiction 📖, and I'm a huge plant lover! 🌵🌱

            <br> <br>

                     
          imageUrl: "/picture.jpeg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Resume
              url: CV/ 
            - name: Publications
              url: papers/
            - name: Musicals
              url: courses/
            - name: Photography
              url: design/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jinjinyan.67@gmail.com
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=HitQqrgAAAAJ
        - name: LinkedIn
          url: jinjin-yan-936300205
        - name: ORCID
          url: https://orcid.org/0000-0002-9278-3115

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Jinjin Yan"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true
